### ISSUE TITLE
get cep后status不显示

### ISSUE THREAD

**Issue by AngusXu** [labring/endpoints-operator#102]
cep是如何与现有的service和endpoint关联起来的？我在cep中加了host和端口，使用tcpSocket，get cep后status那一列始终为空

**Comment by mytting** [comment]
方便贴一下yaml文件吗，以及operator的日志 ，cep的 status 、event 截图

**Comment by AngusXu** [comment]
yaml如下：
apiVersion: sealos.io/v1beta1
kind: ClusterEndpoint
metadata:
  name: test
  namespace: galaxy-esp
spec:
  hosts:
    - 10.251.150.27
  periodSeconds: 10
  ports:
    - name: mysql
      protocol: TCP
      port: 32600
      targetPort: 3306
      tcpSocket:
        enable: true
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1      

cep的 status如下
![1666335350677](https://user-images.githubusercontent.com/10132568/197132301-f549ef57-3ffb-4822-9866-7339ac04be25.png)

另外在readme中能补充怎么查看operator的日志以及event么，不会golang，不清楚怎么操作

**Comment by mytting** [comment]
`kubectl get cep -n galaxy-esp  test -o yaml`
这样看下

**Comment by AngusXu** [comment]
![image](https://user-images.githubusercontent.com/10132568/197133368-6d7db7d2-31b0-444b-9394-22ecbd793fa7.png)

**Comment by mytting** [comment]
@AngusXu 最下面应该有个status字段,贴出来整段yaml吧

**Comment by AngusXu** [comment]
已经贴出了整段yaml，没有status

**Comment by mytting** [comment]
没有finalizer，看下endpoints-operator的日志吧

**Comment by AngusXu** [comment]
sorry，kube-system里的endpoints-operato启动失败了  镜像拉取有问题，没在意看
![image](https://user-images.githubusercontent.com/10132568/197134594-fb4883bc-121b-410e-8b14-92ae4b1c6be4.png)
