### ISSUE TITLE
It is necessary to recreate svc and ep when ep changes

### ISSUE THREAD

**Issue by dundun9** [labring/endpoints-operator#103]
手动指定ep的情况下，ep变化后，kube-proxy维护的ipvs规则内并不会删除旧的转发记录，需要在ep变化时需要重建svc和ep以达到切换效果
![image](https://user-images.githubusercontent.com/50027289/202997464-c8f17aca-d71b-4c29-8ab6-00038ac7cc26.png)

**Comment by mytting** [comment]
需要重建svc，而不是ep

只要ep列表中涉及了去掉其中一个记录 ，就需要重建

ep列表添加一个IP不需要重建


ep里面原来两个IP：
- 原来的没动，添加了一个IP，不需要重建

- 原来的列表中其中一个被移除，需要重建

**Comment by mytting** [comment]
https://github.com/labring/endpoints-operator/issues/12

不需要重建，每个ip一个subset，参考这个issues的格式
