### ISSUE TITLE
more silent

### ISSUE THREAD

**Issue by rkonfj** [labring/endpoints-operator#114]
update the `endpoints` only when inconsistency between the `health list` and `endpoints` is detected.

**Comment by cuisongliu** [comment]
https://github.com/labring/endpoints-operator/issues/103  

Are you talking about this question?

**Comment by cuisongliu** [comment]
Endpoint-operator is to deal with a healthy address, and if it is not healthy, it will not be processed. Just like endpoint only puts the pod address of readliess in endpoint.
