### ISSUE TITLE
通过ClusterEndpoint生成的service如何添加label呢？

### ISSUE THREAD

**Issue by van589** [labring/endpoints-operator#117]

**Comment by cuisongliu** [comment]
什么场景需要这个需求 这个需要改一下代码才可以。

**Comment by van589** [comment]
> 什么场景需要这个需求 这个需要改一下代码才可以。

比如redis和MySQL是Endpoint引入集群，然后Prometheus Operator的ServiceMonitor是需要标签选择器找Service，这时候生成的Service是没有标签的

**Comment by van589** [comment]
> 什么场景需要这个需求 这个需要改一下代码才可以。

是否可以在ClusterEndpoint里自定义生成的Service信息，如label这些

**Comment by cuisongliu** [comment]
> > 什么场景需要这个需求 这个需要改一下代码才可以。
> 
> 是否可以在ClusterEndpoint里自定义生成的Service信息，如label这些

clusterEndpoint 把默认的label 和 annotation 加到svc上
