### ISSUE TITLE
failed to acquire lease kube-system/sealyun-endpoints-operator-leader-election

### ISSUE THREAD

**Issue by jincheng-xiaosu** [labring/endpoints-operator#85]
get  pod logs
I0523 15:43:40.673733       1 round_trippers.go:443] GET https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/sealyun-endpoints-operator-leader-election 200 OK in 5 milliseconds
I0523 15:43:40.674607       1 leaderelection.go:352] lock is held by endpoints-operator-9fcd89d56-g46g5_a83a7451-02e3-4850-a452-e6b9659b082a and has not yet expired
I0523 15:43:40.674624       1 leaderelection.go:247] failed to acquire lease kube-system/sealyun-endpoints-operator-leader-election

**Comment by mytting** [comment]
Is the log of the other POD ok? Only one of the two copies of pods is working normally. In addition, you can try the latest version and use leases to vote
@jincheng-xiaosu
